import { LoginEmail } from "@/screens/LoginEmail";
import Head from "next/head";

const Email = () => {
  return (
    <>
      <Head>
        <title>Login-Email</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <LoginEmail />
    </>
  );
};

export default Email;
